export const products = [
  {
    featured:true,
    price: "13",
    forWhom: "men",
    condition: "new",
    title: "Garlic",
    img: "../assets/sneakers.jpg",
    id: 5,
  },
  {
    featured: true,
    price: "12",
    forWhom: "women",
    condition: "used",
    title: "Cabbage",
    img: "../assets/girl_jacket.jpg",
    id: 1,
  },
  {
    featured: false,
    price: "221",
    forWhom: "kids",
    condition: "new",
    title: "Garlic",
    img: "../assets/shop.jpg",
    id: 2,
  },
  {
    featured: true,
    price: "1342",
    forWhom: "women",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 3,
  },
  {
    featured: true,
    price: "213",
    forWhom: "men",
    condition: "",
    title: "Garlic",
    img: "../assets/newshoes.jpg",
    id: 22,
  },
  {
    featured: true,
    price: "12321",
    forWhom: "men",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 21,
  },
  {
    featured: true,
    price: "241",
    forWhom: "women",
    condition: "",
    title: "Cabbage",
    img: "../assets/girl_jacket.jpg",
    id: 23,
  },
  {
    featured: false,
    price: "231",
    forWhom: "men",
    condition: "",
    title: "Garlic",
    img: "../assets/shoes.jpg",
    id: 24,
  },
  {
    featured: "",
    price: "231",
    forWhom: "kids",
    condition: "",
    title: "Apple",
    img: "../assets/jacket.jpg",
    id: 4,
  },
  {
    featured: "",
    price: "123",
    forWhom: "",
    condition: "",
    title: "Garlic",
    img: "../assets/newshoes.jpg",
    id: 26,
  },
  {
    featured: "",
    price: "231",
    forWhom: "",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 20,
  },
  {
    featured: "",
    price: "",
    forWhom: "",
    condition: "",
    title: "Cabbage",
    img: "../assets/girl_jacket.jpg",
    id: 25,
  },
  {
    featured: "",
    price: "",
    forWhom: "",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 6,
  },
  {
    featured: "",
    price: "",
    forWhom: "",
    condition: "",
    title: "Garlic",
    img: "../assets/newshoes.jpg",
    id: 7,
  },
  {
    featured: "",
    price: "",
    forWhom: "",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 8,
  },
  {
    featured: "true",
    price: "",
    forWhom: "",
    condition: "",
    title: "Cabbage",
    img: "../assets/girl_jacket.jpg",
    id: 9,
  },
  {
    featured: "true",
    price: "",
    forWhom: "",
    condition: "",
    title: "Garlic",
    img: "../assets/newshoes.jpg",
    id: 10,
  },
  {
    featured: "true",
    price: "",
    forWhom: "",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 13,
  },
  {
    featured: "false",
    price: "",
    forWhom: "",
    condition: "",
    title: "Garlic",
    img: "../assets/newshoes.jpg",
    id: 14,
  },
  {
    featured: true,
    price: "",
    forWhom: "women",
    condition: "",
    title: "Apple",
    img: "../assets/girl_shoes.jpg",
    id: 15,
  },
];
